LOG_LEVEL: INFO

SAMPLING_WAIT_TIME: 0.25

# Set pin number as less than or equal to 0 to be ignored
FP_HEADERS_WRITE:
  POWER_BUTTON_PIN: 16
  #RESET_BUTTON_PIN: 0

FP_HEADERS_READ:
  POWER_LED_PIN: 18
  HDD_LED_PIN: 11
  #PC_SPEAKER_PIN: 0
